addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"       % "1.3.6")
addSbtPlugin("org.scalastyle"     %%  "scalastyle-sbt-plugin"   % "1.0.0")
addSbtPlugin("org.scoverage"      %   "sbt-scoverage"           % "1.5.1")
addSbtPlugin("org.scoverage"      %   "sbt-coveralls"           % "1.2.5")
addSbtPlugin("com.codacy"         %   "sbt-codacy-coverage"     % "1.3.11")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"      % "0.9.0")
